apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- flux-system/flux.yaml
- aad-pod-identity.yaml
- akv-secrets-store-csi.yaml
- kured.yaml
images:
- name: docker.io/weaveworks/kured
  newName: acraks2zlevmmi4vng2.azurecr.io/weaveworks/kured
- name: docker.io/fluxcd/flux
  newName: acraks2zlevmmi4vng2.azurecr.io/fluxcd/flux
- name: docker.io/library/memcached
  newName: acraks2zlevmmi4vng2.azurecr.io/library/memcached